# Generated by Django 6.0.5 on 2026-05-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image',
            field=models.ImageField(default='projects/default.jpg', upload_to='projects/'),
            preserve_default=False,
        ),
    ]
