# Generated by Django 6.0.5 on 2026-05-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(default='projects/default.jpg', upload_to='projects/'),
        ),
    ]
