# Generated by Django 6.0.5 on 2026-05-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_partenaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
