# Generated by Django 6.0.5 on 2026-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_actualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
